name: Run Test Suite 
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.0"
          - "1.6"
          - "1.9"
          - "nightly"
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: "1.0"
            allow_failure: true
          - version: "1.6"
            allow_failure: true
          - version: "1.9"
            allow_failure: false
          - version: "nightly"
            allow_failure: true
    steps:
      - uses: actions/checkout@v4

      # Install test dependencies
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: expect
          version: 1.0

      #  Install Julia
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache everything
      - uses: julia-actions/cache@v1

      # Run the tests
      - uses: julia-actions/julia-runtest@latest
